from enum import Enum


class Layout(Enum):
    SIMPLE = "simple"
    PLAIN = "plain"
    GRID = "grid"
    SIMPLE_GRID = "simple_grid"
    ROUNDED_GRID = "rounded_grid"
    HEAVY_GRID = "heavy_grid"
    MIXED_GRID = "mixed_grid"
    DOUBLE_GRID = "double_grid"
    FANCY_GRID = "fancy_grid"
    OUTLINE = "outline"
    SIMPLE_OUTLINE = "simple_outline"
    ROUNDED_OUTLINE = "rounded_outline"
    HEAVY_OUTLINE = "heavy_outline"
    MIXED_OUTLINE = "mixed_outline"
    DOUBLE_OUTLINE = "double_outline"
    FANCY_OUTLINE = "fancy_outline"
    GITHUB = "github"
    PIPE = "pipe"
    ORGTBL = "orgtbl"
    JIRA = "jira"
    PRESTO = "presto"
    PRETTY = "pretty"
    PSQL = "psql"
    RST = "rst"
    MEDIAWIKI = "mediawiki"
    MOINMOIN = "moinmoin"
    YOUTRACK = "youtrack"
    HTML = "html"
    UNSAFEHTML = "unsafehtml"
    LATEX = "latex"
    LATEX_RAW = "latex_raw"
    LATEX_BOOKTABS = "latex_booktabs"
    LATEX_LONGTABLE = "latex_longtable"
    TSV = "tsv"
    TEXTILE = "textile"
    ASCIIDOC = "asciidoc"
