from enum import Enum


class Win32SoundDevice(Enum):
    Availability = 'Availability'
    Caption = 'Caption'
    ConfigManagerErrorCode = 'Config Manager Error Code'
    ConfigManagerUserConfig = 'Config Manager User Config'
    CreationClassName = 'Creation Class Name'
    Description = 'Description'
    DeviceID = 'Device ID'
    DMABufferSize = 'DMA Buffer Size'
    ErrorCleared = 'Error Cleared'
    ErrorDescription = 'Error Description'
    InstallDate = 'Install Date'
    LastErrorCode = 'Last Error Code'
    Manufacturer = 'Manufacturer'
    MPU401Address = 'MPU401 Address'
    Name = 'Name'
    PNPDeviceID = 'PNP Device ID'
    PowerManagementCapabilities = 'Power Management Capabilities'
    PowerManagementSupported = 'Power Management Supported'
    ProductName = 'Product Name'
    Status = 'Status'
    StatusInfo = 'Status Info'
    SystemCreationClassName = 'System Creation Class Name'
    SystemName = 'System Name'
