from enum import Enum


class Win32PnP(Enum):
    Availability = 'Availability'
    Caption = 'Caption'
    ClassGuid = 'ClassGuid'
    CompatibleID = 'CompatibleID'
    ConfigManagerErrorCode = 'ConfigManagerErrorCode'
    ConfigManagerUserConfig = 'ConfigManagerUserConfig'
    CreationClassName = 'CreationClassName'
    Description = 'Description'
    DeviceID = 'DeviceID'
    ErrorCleared = 'ErrorCleared'
    ErrorDescription = 'ErrorDescription'
    HardwareID = 'HardwareID'
    InstallDate = 'InstallDate'
    LastErrorCode = 'LastErrorCode'
    Manufacturer = 'Manufacturer'
    Name = 'Name'
    PNPClass = 'PNPClass'
    PNPDeviceID = 'PNPDeviceID'
    PowerManagementCapabilities = 'PowerManagementCapabilities'
    PowerManagementSupported = 'PowerManagementSupported'
    Present = 'Present'
    Service = 'Service'
    Status = 'Status'
    StatusInfo = 'StatusInfo'
    SystemCreationClassName = 'SystemCreationClassName'
    SystemName = 'SystemName'
