from enum import Enum


class Win32NetworkAdapter(Enum):
    Name = 'Name'
    MACAddress = 'MAC Address'
    AdapterType = 'Adapter Type'
    Speed = 'Speed'
    AdapterTypeID = 'Adapter Type ID'
    AutoSense = 'Auto Sense'
    Availability = 'Availability'
    Caption = 'Caption'
    ConfigManagerErrorCode = 'Config Manager Error Code'
    ConfigManagerUserConfig = 'Config Manager User Config'
    CreationClassName = 'Creation Class Name'
    Description = 'Description'
    DeviceID = 'Device ID'
    ErrorCleared = 'Error Cleared'
    ErrorDescription = 'Error Description'
    GUID = 'GUID'
    Index = 'Index'
    InstallDate = 'Install Date'
    Installed = 'Installed'
    InterfaceIndex = 'Interface Index'
    LastErrorCode = 'Last Error Code'
    Manufacturer = 'Manufacturer'
    MaxNumberControlled = 'Max Number Controlled'
    MaxSpeed = 'Max Speed'
    NetConnectionID = 'Net Connection ID'
    NetConnectionStatus = 'Net Connection Status'
    NetEnabled = 'Net Enabled'
    NetworkAddresses = 'Network Addresses'
    PermanentAddress = 'Permanent Address'
    PhysicalAdapter = 'Physical Adapter'
    PNPDeviceID = 'PNP Device ID'
    PowerManagementCapabilities = 'Power Management Capabilities'
    PowerManagementSupported = 'Power Management Supported'
    ProductName = 'Product Name'
    ServiceName = 'Service Name'
    Status = 'Status'
    StatusInfo = 'Status Info'
    SystemCreationClassName = 'System Creation Class Name'
    SystemName = 'System Name'
    TimeOfLastReset = 'Time Of Last Reset'
