from enum import Enum


class Win32PortableBattery(Enum):
    Availability = 'Availability'
    BatteryStatus = 'Battery Status'
    CapacityMultiplier = 'Capacity Multiplier'
    Caption = 'Caption'
    Chemistry = 'Chemistry'
    ConfigManagerErrorCode = 'Config Manager Error Code'
    ConfigManagerUserConfig = 'Config Manager User Config'
    CreationClassName = 'Creation Class Name'
    Description = 'Description'
    DesignCapacity = 'Design Capacity'
    DesignVoltage = 'Design Voltage'
    DeviceID = 'Device ID'
    ErrorCleared = 'Error Cleared'
    ErrorDescription = 'Error Description'
    EstimatedChargeRemaining = 'Estimated Charge Remaining'
    EstimatedRunTime = 'Estimated Run Time'
    ExpectedLife = 'Expected Life'
    FullChargeCapacity = 'Full Charge Capacity'
    InstallDate = 'Install Date'
    LastErrorCode = 'Last Error Code'
    Location = 'Location'
    ManufactureDate = 'Manufacture Date'
    Manufacturer = 'Manufacturer'
    MaxBatteryError = 'Max Battery Error'
    MaxRechargeTime = 'Max Recharge Time'
    Name = 'Name'
    PNPDeviceID = 'PNP Device ID'
    PowerManagementCapabilities = 'Power Management Capabilities'
    PowerManagementSupported = 'Power Management Supported'
    SmartBatteryVersion = 'Smart Battery Version'
    Status = 'Status'
    StatusInfo = 'Status Info'
    SystemCreationClassName = 'System Creation Class Name'
    SystemName = 'System Name'
    TimeOnBattery = 'Time On Battery'
    TimeToFullCharge = 'Time To Full Charge'
