from enum import Enum


class Win32BaseBoard(Enum):
    Caption = 'Caption'
    ConfigOptions = 'Config Options'
    CreationClassName = 'Creation Class Name'
    Depth = 'Depth'
    Description = 'Description'
    Height = 'Height'
    HostingBoard = 'Hosting Board'
    HotSwappable = 'Hot Swappable'
    InstallDate = 'Install Date'
    Manufacturer = 'Manufacturer'
    Model = 'Model'
    Name = 'Name'
    OtherIdentifyingInfo = 'Other Identifying Info'
    PartNumber = 'Part Number'
    PoweredOn = 'Powered On'
    Product = 'Product'
    Removable = 'Removable'
    Replaceable = 'Replaceable'
    RequirementsDescription = 'Requirements Description'
    RequiresDaughterBoard = 'Requires Daughter Board'
    SerialNumber = 'Serial Number'
    SKU = 'SKU'
    SlotLayout = 'Slot Layout'
    SpecialRequirements = 'Special Requirements'
    Status = 'Status'
    Tag = 'Tag'
    Version = 'Version'
    Weight = 'Weight'
    Width = 'Width'
