from enum import Enum


class Win32Battery(Enum):
    Availability = 'Availability'
    BatteryRechargeTime = 'Battery Recharge Time'
    BatteryStatus = 'Battery Status'
    Caption = 'Caption'
    ConfigManagerErrorCode = 'Config Manager Error Code'
    ConfigManagerUserConfig = 'Config Manager User Config'
    CreationClassName = 'Creation Class Name'
    Description = 'Description'
    DeviceID = 'Device ID'
    ErrorCleared = 'Error Cleared'
    ErrorDescription = 'Error Description'
    EstimatedChargeRemaining = 'Estimated Charge Remaining'
    EstimatedRunTime = 'Estimated Run Time'
    ExpectedBatteryLife = 'Expected Battery Life'
    ExpectedLife = 'Expected Life'
    FullChargeCapacity = 'Full Charge Capacity'
    InstallDate = 'Install Date'
    LastErrorCode = 'Last Error Code'
    MaxRechargeTime = 'Max Recharge Time'
    Name = 'Name'
    PNPDeviceID = 'PNP Device ID'
    PowerManagementCapabilities = 'Power Management Capabilities'
    PowerManagementSupported = 'Power Management Supported'
    SmartBatteryVersion = 'Smart Battery Version'
    Status = 'Status'
    StatusInfo = 'Status Info'
    SystemCreationClassName = 'System Creation Class Name'
    SystemName = 'System Name'
    TimeOnBattery = 'Time on Battery'
    TimeToFullCharge = 'Time to Full Charge'
