from enum import Enum


class Win32Volume(Enum):
    Access = 'Access'
    Automount = 'Automount'
    Availability = 'Availability'
    BlockSize = 'Block Size'
    BootVolume = 'Boot Volume'
    Capacity = 'Capacity'
    Caption = 'Caption'
    Compressed = 'Compressed'
    ConfigManagerErrorCode = 'Config Manager Error Code'
    ConfigManagerUserConfig = 'Config Manager User Config'
    CreationClassName = 'Creation Class Name'
    Description = 'Description'
    DeviceID = 'Device ID'
    DirtyBitSet = 'Dirty Bit Set'
    DriveLetter = 'Drive Letter'
    DriveType = 'Drive Type'
    ErrorCleared = 'Error Cleared'
    ErrorDescription = 'Error Description'
    ErrorMethodology = 'Error Methodology'
    FileSystem = 'File System'
    FreeSpace = 'Free Space'
    IndexingEnabled = 'Indexing Enabled'
    InstallDate = 'Install Date'
    Label = 'Label'
    LastErrorCode = 'Last Error Code'
    MaximumFileNameLength = 'Maximum File Name Length'
    Name = 'Name'
    NumberOfBlocks = 'Number Of Blocks'
    PageFilePresent = 'Page File Present'
    PNPDeviceID = 'PNP Device ID'
    PowerManagementCapabilities = 'Power Management Capabilities'
    PowerManagementSupported = 'Power Management Supported'
    Purpose = 'Purpose'
    QuotasEnabled = 'Quotas Enabled'
    QuotasIncomplete = 'Quotas Incomplete'
    QuotasRebuilding = 'Quotas Rebuilding'
    SerialNumber = 'Serial Number'
    Status = 'Status'
    StatusInfo = 'Status Info'
    SupportsDiskQuotas = 'Supports Disk Quotas'
    SupportsFileBasedCompression = 'Supports File Based Compression'
    SystemCreationClassName = 'System Creation Class Name'
    SystemName = 'System Name'
    SystemVolume = 'System Volume'
