from enum import Enum


class Win32VoltageProbe(Enum):
    Accuracy = 'Accuracy'
    Availability = 'Availability'
    Caption = 'Caption'
    ConfigManagerErrorCode = 'Config Manager Error Code'
    ConfigManagerUserConfig = 'Config Manager User Config'
    CreationClassName = 'Creation Class Name'
    CurrentReading = 'Current Reading'
    Description = 'Description'
    DeviceID = 'Device ID'
    ErrorCleared = 'Error Cleared'
    ErrorDescription = 'Error Description'
    InstallDate = 'Install Date'
    IsLinear = 'Is Linear'
    LastErrorCode = 'Last Error Code'
    LowerThresholdCritical = 'Lower Threshold Critical'
    LowerThresholdFatal = 'Lower Threshold Fatal'
    LowerThresholdNonCritical = 'Lower Threshold Non Critical'
    MaxReadable = 'Max Readable'
    MinReadable = 'Min Readable'
    Name = 'Name'
    NominalReading = 'Nominal Reading'
    NormalMax = 'Normal Max'
    NormalMin = 'Normal Min'
    PNPDeviceID = 'PNP Device ID'
    PowerManagementCapabilities = 'Power Management Capabilities'
    PowerManagementSupported = 'Power Management Supported'
    Resolution = 'Resolution'
    Status = 'Status'
    StatusInfo = 'Status Info'
    SystemCreationClassName = 'System Creation Class Name'
    SystemName = 'System Name'
    Tolerance = 'Tolerance'
    UpperThresholdCritical = 'Upper Threshold Critical'
    UpperThresholdFatal = 'Upper Threshold Fatal'
    UpperThresholdNonCritical = 'Upper Threshold Non Critical'
