from enum import Enum


class Win32MemoryDevice(Enum):
    Access = 'Access'
    AdditionalErrorData = 'Additional Error Data'
    Availability = 'Availability'
    BlockSize = 'Block Size'
    Caption = 'Caption'
    ConfigManagerErrorCode = 'Config Manager Error Code'
    ConfigManagerUserConfig = 'Config Manager User Config'
    CorrectableError = 'Correctable Error'
    CreationClassName = 'Creation Class Name'
    Description = 'Description'
    DeviceID = 'Device ID'
    EndingAddress = 'Ending Address'
    ErrorAccess = 'Error Access'
    ErrorAddress = 'Error Address'
    ErrorCleared = 'Error Cleared'
    ErrorData = 'Error Data'
    ErrorDataOrder = 'Error Data Order'
    ErrorDescription = 'Error Description'
    ErrorGranularity = 'Error Granularity'
    ErrorInfo = 'Error Info'
    ErrorMethodology = 'Error Methodology'
    ErrorResolution = 'Error Resolution'
    ErrorTime = 'Error Time'
    ErrorTransferSize = 'Error Transfer Size'
    InstallDate = 'Install Date'
    LastErrorCode = 'Last Error Code'
    Name = 'Name'
    NumberOfBlocks = 'Number of Blocks'
    OtherErrorDescription = 'Other Error Description'
    PNPDeviceID = 'PNP Device ID'
    PowerManagementCapabilities = 'Power Management Capabilities'
    PowerManagementSupported = 'Power Management Supported'
    Purpose = 'Purpose'
    StartingAddress = 'Starting Address'
    Status = 'Status'
    StatusInfo = 'Status Info'
    SystemCreationClassName = 'System Creation Class Name'
    SystemLevelAddress = 'System Level Address'
    SystemName = 'System Name'
