from enum import Enum


class Win32DiskPartition(Enum):
    Access = 'Access'
    Availability = 'Availability'
    BlockSize = 'Block Size'
    Bootable = 'Bootable'
    BootPartition = 'Boot Partition'
    Caption = 'Caption'
    ConfigManagerErrorCode = 'Config Manager Error Code'
    ConfigManagerUserConfig = 'Config Manager User Config'
    CreationClassName = 'Creation Class Name'
    Description = 'Description'
    DeviceID = 'Device ID'
    DiskIndex = 'Disk Index'
    ErrorCleared = 'Error Cleared'
    ErrorDescription = 'Error Description'
    ErrorMethodology = 'Error Methodology'
    HiddenSectors = 'Hidden Sectors'
    Index = 'Index'
    InstallDate = 'Install Date'
    LastErrorCode = 'Last Error Code'
    Name = 'Name'
    NumberOfBlocks = 'Number Of Blocks'
    PNPDeviceID = 'PNP Device ID'
    PowerManagementCapabilities = 'Power Management Capabilities'
    PowerManagementSupported = 'Power Management Supported'
    PrimaryPartition = 'Primary Partition'
    Purpose = 'Purpose'
    RewritePartition = 'Rewrite Partition'
    Size = 'Size'
    StartingOffset = 'Starting Offset'
    Status = 'Status'
    StatusInfo = 'Status Info'
    SystemCreationClassName = 'System Creation Class Name'
    SystemName = 'System Name'
    Type = 'Type'
