from enum import Enum


class Win32PhysicalMemory(Enum):
    Capacity = 'Capacity'
    Speed = 'Speed'
    Manufacturer = 'Manufacturer'
    BankLabel = 'Bank Label'
    DataWidth = 'Data Width'
    Description = 'Description'
    DeviceLocator = 'Device Locator'
    FormFactor = 'Form Factor'
    HotSwappable = 'Hot Swappable'
    InstallDate = 'Install Date'
    InterleaveDataDepth = 'Interleave Data Depth'
    InterleavePosition = 'Interleave Position'
    MaxVoltage = 'Max Voltage'
    MemoryType = 'Memory Type'
    MinVoltage = 'Min Voltage'
    Model = 'Model'
    Name = 'Name'
    OtherIdentifyingInfo = 'Other Identifying Info'
    PartNumber = 'Part Number'
    PositionInRow = 'Position In Row'
    PoweredOn = 'Powered On'
    Removable = 'Removable'
    Replaceable = 'Replaceable'
    SerialNumber = 'Serial Number'
    SKU = 'SKU'
    Status = 'Status'
    Tag = 'Tag'
    TotalWidth = 'Total Width'
    TypeDetail = 'Type Detail'
    Version = 'Version'
