from enum import Enum


class Win32Bios(Enum):
    BIOSVersion = 'BIOS Version'
    Manufacturer = 'Manufacturer'
    ReleaseDate = 'Release Date'
    BuildNumber = 'Build Number'
    Caption = 'Caption'
    CodeSet = 'Code Set'
    CurrentLanguage = 'Current Language'
    Description = 'Description'
    IdentificationCode = 'Identification Code'
    InstallableLanguages = 'Installable Languages'
    InstallDate = 'Install Date'
    LanguageEdition = 'Language Edition'
    ListOfLanguages = 'List Of Languages'
    Name = 'Name'
    OtherTargetOS = 'Other Target OS'
    PrimaryBIOS = 'Primary BIOS'
    SerialNumber = 'Serial Number'
    SMBIOSBIOSVersion = 'SMBIOS BIOS Version'
    SMBIOSMajorVersion = 'SMBIOS Major Version'
    SMBIOSMinorVersion = 'SMBIOS Minor Version'
    SMBIOSPresent = 'SMBIOS Present'
    SoftwareElementID = 'Software Element ID'
    SoftwareElementState = 'Software Element State'
    Status = 'Status'
    TargetOperatingSystem = 'Target Operating System'
    Version = 'Version'
